PokemonPackage/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokemonPackage/main/default/objects/Pokemon__c/fields/Average_Damage__c.field-meta.xml
<CustomField>
    <fullName>Average_Damage__c</fullName>
    <formula>General_Damage__c /2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Damage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PokemonPackage/main/default/objects/Pokemon__c/fields/Defense__c.field-meta.xml
<CustomField>
    <fullName>Defense__c</fullName>
    <formula>Base_Defense__c + ( Base_Defense__c * Level__c * 0.65)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Defense</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokemonPackage/main/default/objects/Pokemon__c/fields/HP__c.field-meta.xml
<CustomField>
    <fullName>HP__c</fullName>
    <formula>Base_HP__c + ( Level__c * 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PokemonPackage/main/default/objects/Pokemon__c/fields/Pokemon_Back__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_Back__c</fullName>
    <label>Pokemon Back</label>
    <type>Url</type>
</CustomField>

PokemonPackage/main/default/objects/Pokemon__c/fields/Pokemon_Front__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_Front__c</fullName>
    <label>Pokemon_Front</label>
    <type>Url</type>
</CustomField>

PokemonPackage/main/default/objects/Pokemon__c/fields/Pokemon_Name__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_Name__c</fullName>
    <label>Pokemon Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

PokemonPackage/main/default/classes/pokemonClass.cls
public with sharing class pokemonClass {

    @AuraEnabled(Cacheable=true)
    public static List<Pokemon__c> getPokemonList(){
        try {
            return [SELECT Name, Pokemon_Name__c, Type__c, HP__c, Average_Damage__c, Defense__c, Pokemon_Front__c, Pokemon_Back__c
             FROM Pokemon__c WHERE OwnerId =: UserInfo.getUserId() WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(Cacheable=true)
    public static List<Pokemon__c> searchPokemon(String searchTerm){
        searchTerm = searchTerm.trim();
        if(searchTerm ==''){
            return getPokemonList();
        }
        else{
            searchTerm = '%' + searchTerm + '%';
            return [SELECT Name, Pokemon_Name__c, Type__c, HP__c, Average_Damage__c, Defense__c, Pokemon_Front__c, Pokemon_Back__c
             FROM Pokemon__c WHERE Pokemon_Name__c LIKE :searchTerm AND OwnerId =: UserInfo.getUserId() WITH SECURITY_ENFORCED];
        }
    }
}